version = 0.1

# Run local API:
#   - $ sam build
#   - $ sam local start-api
[default.local_start_api.parameters]
region = "eu-central-1"
parameter_overrides = [
    "Env=dev",
]

# Deploy to Development environment:
#   - $ sam build
#   - $ sam deploy --config-env dev --profile {your-aws-profile}
[dev.deploy.parameters]
stack_name = "ede-demo-pokemon-api-dev"
region = "eu-central-1"
s3_bucket = "pokemon-battle-simulator-sam-deploy-s3-bucket"  # TODO: Replace with your S3 bucket name
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Env=dev",
]

# Deploy to Production environment:
#   - $ sam build
#   - $ sam deploy --config-env prod --profile {your-aws-profile}
[prod.deploy.parameters]
stack_name = "ede-demo-pokemon-api-prod"
region = "eu-central-1"
s3_bucket = "pokemon-battle-simulator-sam-deploy-s3-bucket"  # TODO: Replace with your S3 bucket name
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Env=prod",
]