version = 0.1

# Run local API:
#   - $ sam build
#   - $ sam local start-api
[default.local_start_api.parameters]
region = "eu-central-1"
parameter_overrides = [
    "Env=dev",
]

# Deploy to Development environment:
#   - $ sam build
#   - $ sam deploy --config-env dev
[dev.deploy.parameters]
stack_name = "ede-demo-pokemon-api-dev"
region = "eu-central-1"
s3_bucket = "pokemon-battle-similator-sam-deploy"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Env=dev",
]

# Deploy to Production environment:
#   - $ sam build
#   - $ sam deploy --config-env prod
[prod.deploy.parameters]
stack_name = "ede-demo-pokemon-api-prod"
region = "eu-central-1"
s3_bucket = "pokemon-battle-similator-sam-deploy"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Env=prod",
]